### ISSUE TITLE
What is maximum speed?

### ISSUE THREAD

**Issue by bakwc** [sdima1357/esp32_usb_soft_host#3]
Hey! Thank you for awesome library! What is the maximum possible speed (approximately)?

**Comment by sdima1357** [comment]
Speed of what? The code imlements USB-LS HOST Interface  controller - 1.5Mbit/s 

Low speed | LS | 1.5 Mbit/s (187.5 KB/s) | USB 1.0
From :
https://en.wikipedia.org/wiki/USB_(Communications)
