### ISSUE TITLE
Game pad support?

### ISSUE THREAD

**Issue by ccc9090** [sdima1357/esp32_usb_soft_host#4]
Hello,

I am new to circuits and arduino so I am sorry if these are dump/simple questions.

I am trying to use a esp32 adafruit feather to turn a wired usb gamepad into a wireless one for pc. I have the gamepad to bluetooth part (https://github.com/lemmingDev/ESP32-BLE-Gamepad) but I need to get the usb gamepad to be readable to that code. Would your code work or partly work for that?

**Comment by sdima1357** [comment]
May be work. I don't know, but You can try it with **Your** usb gamepad.  3 of 3 my different joysticks - work without problems
