### ISSUE TITLE
USB Pen Drive support?

### ISSUE THREAD

**Issue by Miguel0101** [sdima1357/esp32_usb_soft_host#5]

**Comment by sdima1357** [comment]
I have no idea about it.  Can You  try and send me some logs?

**Comment by Miguel0101** [comment]
![log](https://user-images.githubusercontent.com/56565368/129096216-862681cd-be52-4ed6-b61d-daaccc732d41.png)

**Comment by sdima1357** [comment]
Seems like Your device is Full speed USB device(not supported).  "The program"  had no start transactions with it.

**Comment by Miguel0101** [comment]
> Seems like Your device is Full speed USB device(not supported). "The program" had no start transactions with it.

How like?

**Comment by Miguel0101** [comment]
I closed this issue because USB Pen Drive is not supported.
